POSTGRESQL = 'postgresql'
SQLITE3 = 'sqlite3'

AVAILABLE_DATABASES = [POSTGRESQL, SQLITE3]

POSTGRESQL_DB_NAME = 'pytest'
POSTGRESQL_USER = 'pytester'
POSTGRESQL_PASSWORD = 'asdf'
POSTGRESQL_HOST = '127.0.0.1'
POSTGRESQL_PORT = '1115'

SQLITE3_LOCATION = 'db/sqlite3_test.db'

